# #23. Throwing and catching exceptions (Part 1)

Exception handling in C++ is about *throwing* and *catching* exceptions. So let's begin with some pseudo-code outlining roughly how it looks to throw and catch C++ exceptions.

```cpp
void SomeFunction() {
    // If something exceptional happens, then
    throw /* an exception type */;
}

int main()
{
    try
    {
        // Guarded code
        SomeFunction();
    }
    catch (/* an exception type */)
    {
        // Take appropriate action
    }
}
```

The story begins with the [`try`](https://docs.microsoft.com/cpp/cpp/try-throw-and-catch-statements-cpp) keyword, which guards a block of code. The `try` block can contain as much code as you like; all of it is guarded by the `catch` block (or blocks, as we'll see) that come after it. When the [`throw`](https://docs.microsoft.com/cpp/cpp/try-throw-and-catch-statements-cpp) keyword throws (or raises) an exception of some type, control passes immediately to the `catch` block that matches the exception type.

We'll look at different types of exceptions soon. You can think of a `catch` block as an exception handler.

|Prev|Next|Contents|
|-|-|-|
|[#22. Error handling (Part 2)](022.md)|[#24. Throwing and catching exceptions (Part 2)](024.md)|[Bite-sized C++](../README.md)|
